### ISSUE TITLE
download_path = "C:/Users/myeongjun/github/AutoCrawler/download/"

### ISSUE THREAD

**Issue by fabiatan** [leaderj1001/Billion-scale-semi-supervised-learning#1]
Hi,
may i know how can i get this dataset?

**Comment by leaderj1001** [comment]
I can not share data because it is crawled, and you need to collect data through the image crawl example.
I'm sorry to be late for your reply.

**Comment by kanzaali** [comment]
what image crawl example. can you please guide me how can I get this data?

**Comment by leaderj1001** [comment]
Thanks for your comments !

We crawled and used CIFAR-100 dataset classes.
You can find a dataset info. https://www.cs.toronto.edu/~kriz/cifar.html
We use a chromedriver.
https://github.com/leaderj1001/Billion-scale-semi-supervised-learning/tree/master/image_crawler

Thank you.

Best regards,

Myeongjun Kim

2020년 7월 7일 (화) 오후 12:22, kanza <notifications@github.com>님이 작성:

**Comment by kanzaali** [comment]
Thank you for your response.

What if I download CIFAR100 directly from this website:
https://www.cs.toronto.edu/~kriz/cifar.html

Regards,
Kanza
